perl gl_expand_5loc.pl ./pull/pop_CAU_gl.txt ./pull/glid.CAU.txt ./pull/pull.CAU.txt
perl gl_expand_5loc.pl ./pull/AAFA_CARB_DONOR_MASTER_flatt_for_em.txt ./pull/glid.AAFA_CARB.txt ./pull/pull.AAFA_CARB.txt
perl gl_expand_5loc.pl ./pull/AAFA_NAMER_DONOR_MASTER_flatt_for_em.txt ./pull/glid.AAFA_NAMER.txt ./pull/pull.AAFA_NAMER.txt
perl gl_expand_5loc.pl ./pull/FILII_NAMER_DONOR_MASTER_flatt_for_em.txt ./pull/glid.FILII_NAMER.txt ./pull/pull.FILII_NAMER.txt
perl gl_expand_5loc.pl ./pull/MENAFC_NAMER_DONOR_MASTER_flatt_for_em.txt ./pull/glid.MENAFC_NAMER.txt ./pull/pull.MENAFC_NAMER.txt
perl gl_expand_5loc.pl ./pull/AAFA_CARB_DONOR_MASTER_flatt_for_em_3000.txt ./pull/glid.AAFA_CARB_3000.txt ./pull/pull.AAFA_CARB_3000.txt
perl gl_expand_5loc.pl ./pull/AAFA_NAMER_DONOR_MASTER_flatt_for_em_3000.txt ./pull/glid.AAFA_NAMER_3000.txt ./pull/pull.AAFA_NAMER_3000.txt
perl gl_expand_5loc.pl ./pull/FILII_NAMER_DONOR_MASTER_flatt_for_em_3000.txt ./pull/glid.FILII_NAMER_3000.txt ./pull/pull.FILII_NAMER_3000.txt
perl gl_expand_5loc.pl ./pull/MENAFC_NAMER_DONOR_MASTER_flatt_for_em_3000.txt ./pull/glid.MENAFC_NAMER_3000.txt ./pull/pull.MENAFC_NAMER_3000.txt
perl gl_expand_5loc.pl ./pull/don_post_mr.gl.txt ./pull/glid.MR.txt ./pull/pull.MR.txt
perl gl_expand_5loc.pl ./pull/don_post_mr_1000.gl.txt ./pull/glid.MR_1000.txt ./pull/pull.MR_1000.txt
perl gl_expand_5loc.pl ./pull/don_post_mr_10000.gl.txt ./pull/glid.MR_10000.txt ./pull/pull.MR_10000.txt
perl gl_expand_5loc.pl ./pull/don_post_mr_3000.gl.txt ./pull/glid.MR_3000.txt ./pull/pull.MR_3000.txt